from enum import Enum


class TiposDeRelatoriosEnum(Enum):
    AGENT_ACTIONS_HISTORICO = 1
    CALL_HISTORY_HISTORICO = 2
    DIALER_CALLS_HISTORICO = 3
    HISTORICO_CALLBACK = 4
    PESQUISA_SATISFACAO = 5
